# Generated by Django 5.2.13 on 2026-08-18 22:20

from collections import defaultdict

from django.db import migrations, models
from django.db.models.functions import Lower


def merge_duplicate_service_types(apps, schema_editor):
    """Keep one ServiceType per case-insensitive name; retarget jobs, drop extras."""
    ServiceType = apps.get_model("main", "ServiceType")
    Job = apps.get_model("main", "Job")
    groups = defaultdict(list)
    for row in ServiceType.objects.all().order_by("id"):
        key = " ".join((row.name or "").casefold().split())
        groups[key].append(row)
    for rows in groups.values():
        if len(rows) < 2:
            continue
        keeper = rows[0]
        extra_ids = [row.id for row in rows[1:]]
        Job.objects.filter(service_type_id__in=extra_ids).update(service_type_id=keeper.id)
        ServiceType.objects.filter(id__in=extra_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_bankaccount_iban_encrypted_length"),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_service_types, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="servicetype",
            constraint=models.UniqueConstraint(
                Lower("name"),
                name="main_servicetype_name_lower_uniq",
            ),
        ),
    ]
